version: "3.6"

services:
  #Backend API
  face-detection-api:
    container_name: Faces-Backend
    build: ./
    command: npm start
    working_dir: /usr/src/face-detection-api
    environment:
      POSTGRES_URI: postgres://shion:secret@postgres:5432/face-detection-api-docker
      # POSTGRES_USER: shion
      # POSTGRES_PASSWORD: secret
      # POSTGRES_DB: smart-brain-docker
      # POSTGRES_HOST: postgres
    links:
      - postgres
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/face-detection-api

  #Postgres
  postgres:
    container_name: Faces-Postgres
    environment:
      POSTGRES_USER: shion
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: face-detection-api-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5434:5432"
